#pragma once

#include "jptmgr.h"
#include <windows.h>

using namespace std;

#include <fstream>

#include <vector>
#ifdef _ICAD
#include "sds.h"
#else
#include	<adslib.h>
#endif

/*:****************************************************************************
名前	drawGirder
機能	鈑桁を作成
戻り値
備考	
******************************************************************************/

void drawGirder(void)
/*:*/
{
	
}

